export enum colorTypes {
    'normal' = '#c4c499',
    'fire' = '#f0a773',
    'fighting' = '#be6f6a',
    'water' = '#a9bceb',
    'flying' = '#cabef0',
    'grass' = '#aad794',
    'poison' = '#ccaccc',
    'electric' = '#f5e39e',
    'ground' = '#e8ce85',
    'psychic' = '#f993b1',
    'rock' = '#cfbd73',
    'ice' = '#b3cdcd',
    'bug' = '#bac656',
    'dragon' = '#9a76f4',
    'ghost' = '#9180ad',
    'dark' = '#8a786b',
    'steel' = '#c6c6db',
    'fairy' = '#eec5c9'
}